py37:
  image: python:3.7
  script:
  - pip install tox
  - tox -e py37

py38:
  image: python:3.8
  script:
  - pip install tox
  - tox -e py38

py39:
  image: python:3.9
  script:
  - pip install tox
  - tox -e py39

py310:
  image: python:3.10
  script:
  - pip install tox
  - tox -e format,mypy,py310,pep8,package
